app = "ping-ino-shop"  # Puedes poner el nombre de tu app Fly.io aquí

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  FLASK_ENV = "production"

[deploy]
  release_command = "python app.py"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
